### ISSUE TITLE
makeRankingPage.js 예외 확인 부탁드립니다!

### ISSUE THREAD

**Issue by KaeHyun** [16OS-final-project/OSSP_final#2]
makeRankingPage.js에서 출력되는 영화 데이터가 7개 미만일때 오류가 발생했습니다!

**Comment by SeoJeongYeop** [comment]
감사합니다. 일단 페이지 로드가 가능하게 바꿨습니다! 추가적으로 디자인까지 고려할 수 있도록 하겠습니다!

**Comment by KaeHyun** [comment]
수정 확인했습니다:)
