### ISSUE TITLE
영화 인터페이스 1,2,3위 배치 수정 확인 부탁드립니다.

### ISSUE THREAD

**Issue by Tro-fish** [16OS-final-project/OSSP_final#3]
영화 리뷰 사이트에서 1,2,3위 카드사이즈가 균일한것 보다는
가운데 있는 1위가 좀 크고 뒤에 2,3위가 살짝 작게 수정 부탁드립니다.

**Comment by KaeHyun** [comment]
div class="container"로 조금 더 정렬되도록 배치 조정완료  
2.3위 코드에 div class="card" 에 style="width: 22rem;"  부분 추가로 사이즈 조정 완료
1위 코드에 div class="card" 에 style="width: 24rem;" 부분 추가로 1위 카드가 가장 크게 설정되도록 조정 완료

** makeRankingPage_edit.js 에서 확인해주시면 됩니다!

**Comment by SeoJeongYeop** [comment]
모바일 환경을 생각하면 1,2,3위 순서대로 나오는 게 더 좋을 것 같습니다!

**Comment by SeoJeongYeop** [comment]
1,2,3위 순서대로 나오도록 수정 완료했습니다!
