### ISSUE TITLE
이미지 경로 문제

### ISSUE THREAD

**Issue by KaeHyun** [16OS-final-project/OSSP_final#4]
`<img src="recommend.png" alt="logo" align: "center"/> `
제 파일에 recommend.png 파일을 추가하고 node app.js 를 실행하면 이미지가 엑스박스가 뜹니다ㅠ
아마 경로 문제인 것 같아서 구글링한 결과 이것저것 해보았는데 잘 해결이 안되네요..
혹시 해결 방법 찾으시면 알려주시면 감사하겠습니다.

**Comment by SeoJeongYeop** [comment]
이미지 파일 경로 문제가 맞습니다! express 모듈을 사용할 때,  파일을 이용할 수 있는 디렉토리를 public으로 설정해두었습니다. recommend.png 파일을 public폴더에 넣어서 웹페이지를 실행하니 이미지 파일이 잘 나오는 것으로 확인되었습니다. 제 답변이 도움이 되었으면 좋겠습니다!
