### ISSUE TITLE
README 체크리스트

### ISSUE THREAD

**Issue by SeoJeongYeop** [16OS-final-project/OSSP_final#6]
# Check List

- [x]  웹 애플리케이션 이름
- [x]  스크린샷 index page, ranking page 상단부, 하단부 3장 정도
- [x]  사용방법
---
- [x]  사용예제
- [x]  설치방법
- [x]  라이센스
- [x]  릴리즈 버전
- [x]  기여 방법
- [x]  리소스 링크
- [x]  Code of Conduct
---
- [x] 데모 영상 링크. YouTube활용

**Comment by KaeHyun** [comment]
전부 다 추가했습니다!
